---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 192.168.0.32
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.0.33
    ports:
      - port: 1