apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-default-cicd3
  annotations:
    pv.beta.kubernetes.io/gid: "0"
spec:
  capacity:
    storage: 10Gi
  accessModes:
      - "ReadWriteOnce"
      - "ReadWriteMany"
  glusterfs:
    endpoints: glusterfs-cluster
    path: dist-vol
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
